### ISSUE TITLE
Semigroup-Monoid issues in GHC 8.4.1-alpha1

### ISSUE THREAD

**Issue by claudeha** [DanielSchuessler/th-expand-syns#10]
compile fails, seems Semigroup is now a superclass of Monoid:

    Building library for th-expand-syns-0.4.3.0..
    [1 of 1] Compiling Language.Haskell.TH.ExpandSyns ( Language/Haskell/TH/ExpandSyns.hs, dist/dist-sandbox-a57ddd46/build/Language/Haskell/TH/ExpandSyns.o )
    
    Language/Haskell/TH/ExpandSyns.hs:88:10: error:
        • No instance for (Semigroup SynonymExpansionSettings)
            arising from the superclasses of an instance declaration
        • In the instance declaration for ‘Monoid SynonymExpansionSettings’
       |
    88 | instance Monoid SynonymExpansionSettings where
       |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Seems there is a patch to make it work at:
https://github.com/hvr/head.hackage/blob/master/patches/th-expand-syns-0.4.3.0.patch
but would need some conditional compilation to still work with earlier GHC.

**Comment by DanielSchuessler** [comment]
Should be fixed now, thanks for pointing it out.
