### ISSUE TITLE
Release for GHC 9?

### ISSUE THREAD

**Issue by ulysses4ever** [DanielSchuessler/th-expand-syns#20]

**Comment by RyanGlScott** [comment]
Some progress was made towards making `master` build with GHC 9.0 in #19, so now we're just [waiting for a new Hackage release](https://github.com/DanielSchuessler/th-expand-syns/pull/19#issuecomment-788532547).

**Comment by ulysses4ever** [comment]
Thanks, Ryan! I saw that work, and here I meant _Hackage_ release in particular.

**Comment by ulysses4ever** [comment]
Great, thank you!
