### ISSUE TITLE
Please release for GHC 8

### ISSUE THREAD

**Issue by goldfirere** [DanielSchuessler/th-expand-syns#6]
HEAD compiles fine with GHC 8, and there will be no further changes to TH in GHC 8. Could you please release to Hackage? Thanks!

**Comment by DanielSchuessler** [comment]
Done! I was still unsure about #5, but I suppose it's better to release it now without support for `substInCon` with GADT arguments (an auxiliary function not directly related to the main task of the package).

**Comment by RyanGlScott** [comment]
This was fixed with the Hackage release of [`th-expand-syns-0.4.0.0`](http://hackage.haskell.org/package/th-expand-syns-0.4.0.0).
