### ISSUE TITLE
A way to suppress warnings about type families

### ISSUE THREAD

**Issue by neongreen** [DanielSchuessler/th-expand-syns#7]
Hi! Is there any way to suppress those warnings? If not (at the moment), could you add an option to suppress them? (If you don't have time, I could make a pull request.)

(Some backstory: we use `th-expand-syns` in our fork of acid-state, and type familes are used a lot in our types. Expanding those type families isn't necessary for acid-state to work correctly, and so the warnings are useless for us.)

**Comment by DanielSchuessler** [comment]
I just pushed a commit to implement this (use `expandSynsWith noWarnTypeFamilies`). Please let me know if it works as intended; I'll upload it to Hackage then :)

**Comment by neongreen** [comment]
Yep, it works.

**Comment by DanielSchuessler** [comment]
OK, uploaded it to Hackage.

**Comment by neongreen** [comment]
Thanks!
